blank_issues_enabled: false
contact_links:
  - name: 📖 README
    url: https://github.com/TOMOSIA-VIETNAM/tms-review-pr#readme
    about: Đọc hướng dẫn cài đặt/dùng/cấu hình trước khi tạo issue, có thể đã trả lời sẵn câu hỏi của bạn.
